#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cpufreq_plus[-1]
	add ucitrack cpufreq_plus
	set ucitrack.@cpufreq_plus[-1].init=cpufreq_plus
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
